training:
  epochs: 100
  patience: 10
  batch_size: 32
  learning_rate: 0.001
  val_ratio: 0.25
  train_data_folders:
    - D:/Uni/Master's/Term1/Fault-Tolerant System Design/Assignments/Replication/code/Dataset1/PCnnLstm/OXFORD/dataset/Cell1_Files
    # - D:/Uni/Master's/Term1/Fault-Tolerant System Design/Assignments/Replication/Implementation\files\PCnnLstm\OXFORD\dataset\Cell1_Files
    # - D:/Uni/Master's/Term1/Fault-Tolerant System Design/Assignments/Replication/Implementation\files\PCnnLstm\OXFORD\dataset\Cell1_Files


testing:
  test_data_folders:
    - D:/Uni/Master's/Term1/Fault-Tolerant System Design/Assignments/Replication/code/Dataset1/PCnnLstm/OXFORD/dataset/Cell2_Files

data:
  sequence_length: 30
  features:
    - Voltage
    - Charge
  target: Temperature